# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import tcpprobe_pb2 as tcpprobe__pb2


class TCPProbeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Add = channel.unary_unary(
                '/main.TCPProbe/Add',
                request_serializer=tcpprobe__pb2.Target.SerializeToString,
                response_deserializer=tcpprobe__pb2.Response.FromString,
                )
        self.Delete = channel.unary_unary(
                '/main.TCPProbe/Delete',
                request_serializer=tcpprobe__pb2.Target.SerializeToString,
                response_deserializer=tcpprobe__pb2.Response.FromString,
                )
        self.Get = channel.unary_stream(
                '/main.TCPProbe/Get',
                request_serializer=tcpprobe__pb2.Target.SerializeToString,
                response_deserializer=tcpprobe__pb2.Stats.FromString,
                )


class TCPProbeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Add(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TCPProbeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Add': grpc.unary_unary_rpc_method_handler(
                    servicer.Add,
                    request_deserializer=tcpprobe__pb2.Target.FromString,
                    response_serializer=tcpprobe__pb2.Response.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=tcpprobe__pb2.Target.FromString,
                    response_serializer=tcpprobe__pb2.Response.SerializeToString,
            ),
            'Get': grpc.unary_stream_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=tcpprobe__pb2.Target.FromString,
                    response_serializer=tcpprobe__pb2.Stats.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'main.TCPProbe', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TCPProbe(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/main.TCPProbe/Add',
            tcpprobe__pb2.Target.SerializeToString,
            tcpprobe__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/main.TCPProbe/Delete',
            tcpprobe__pb2.Target.SerializeToString,
            tcpprobe__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/main.TCPProbe/Get',
            tcpprobe__pb2.Target.SerializeToString,
            tcpprobe__pb2.Stats.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
