# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tcpprobe.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tcpprobe.proto',
  package='main',
  syntax='proto3',
  serialized_options=b'Z$github.com/mehrdadrad/tcpprobe;proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0etcpprobe.proto\x12\x04main\x1a\x1cgoogle/protobuf/struct.proto\"\x81\x01\n\x06Target\x12\x0c\n\x04\x61\x64\x64r\x18\x01 \x01(\t\x12\x10\n\x08interval\x18\x02 \x01(\t\x12(\n\x06labels\x18\x03 \x03(\x0b\x32\x18.main.Target.LabelsEntry\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\")\n\x08Response\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"1\n\x05Stats\x12(\n\x07metrics\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct2\x81\x01\n\x08TCPProbe\x12%\n\x03\x41\x64\x64\x12\x0c.main.Target\x1a\x0e.main.Response\"\x00\x12(\n\x06\x44\x65lete\x12\x0c.main.Target\x1a\x0e.main.Response\"\x00\x12$\n\x03Get\x12\x0c.main.Target\x1a\x0b.main.Stats\"\x00\x30\x01\x42&Z$github.com/mehrdadrad/tcpprobe;protob\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])




_TARGET_LABELSENTRY = _descriptor.Descriptor(
  name='LabelsEntry',
  full_name='main.Target.LabelsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='main.Target.LabelsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='main.Target.LabelsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=184,
)

_TARGET = _descriptor.Descriptor(
  name='Target',
  full_name='main.Target',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='addr', full_name='main.Target.addr', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='interval', full_name='main.Target.interval', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='labels', full_name='main.Target.labels', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_TARGET_LABELSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=184,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='main.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='main.Response.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='main.Response.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=227,
)


_STATS = _descriptor.Descriptor(
  name='Stats',
  full_name='main.Stats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='metrics', full_name='main.Stats.metrics', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=229,
  serialized_end=278,
)

_TARGET_LABELSENTRY.containing_type = _TARGET
_TARGET.fields_by_name['labels'].message_type = _TARGET_LABELSENTRY
_STATS.fields_by_name['metrics'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
DESCRIPTOR.message_types_by_name['Target'] = _TARGET
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['Stats'] = _STATS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Target = _reflection.GeneratedProtocolMessageType('Target', (_message.Message,), {

  'LabelsEntry' : _reflection.GeneratedProtocolMessageType('LabelsEntry', (_message.Message,), {
    'DESCRIPTOR' : _TARGET_LABELSENTRY,
    '__module__' : 'tcpprobe_pb2'
    # @@protoc_insertion_point(class_scope:main.Target.LabelsEntry)
    })
  ,
  'DESCRIPTOR' : _TARGET,
  '__module__' : 'tcpprobe_pb2'
  # @@protoc_insertion_point(class_scope:main.Target)
  })
_sym_db.RegisterMessage(Target)
_sym_db.RegisterMessage(Target.LabelsEntry)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'tcpprobe_pb2'
  # @@protoc_insertion_point(class_scope:main.Response)
  })
_sym_db.RegisterMessage(Response)

Stats = _reflection.GeneratedProtocolMessageType('Stats', (_message.Message,), {
  'DESCRIPTOR' : _STATS,
  '__module__' : 'tcpprobe_pb2'
  # @@protoc_insertion_point(class_scope:main.Stats)
  })
_sym_db.RegisterMessage(Stats)


DESCRIPTOR._options = None
_TARGET_LABELSENTRY._options = None

_TCPPROBE = _descriptor.ServiceDescriptor(
  name='TCPProbe',
  full_name='main.TCPProbe',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=281,
  serialized_end=410,
  methods=[
  _descriptor.MethodDescriptor(
    name='Add',
    full_name='main.TCPProbe.Add',
    index=0,
    containing_service=None,
    input_type=_TARGET,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Delete',
    full_name='main.TCPProbe.Delete',
    index=1,
    containing_service=None,
    input_type=_TARGET,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='main.TCPProbe.Get',
    index=2,
    containing_service=None,
    input_type=_TARGET,
    output_type=_STATS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TCPPROBE)

DESCRIPTOR.services_by_name['TCPProbe'] = _TCPPROBE

# @@protoc_insertion_point(module_scope)
