{
 "title": "TCPProbe Demo",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "TCP RTT",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "tp_tcpinfo_rtt/1000", "legendFormat": "{{target}}" }
   ]
  },
  {
   "title": "TCP Retransmit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "tp_tcpinfo_total_retrans", "legendFormat": "{{target}}" }
   ]
  },
  {
   "title": "TLS Handshake Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "tp_tls_handshake/1000", "legendFormat": "{{target}}" }
   ]
  },
  {
   "title": "Connect Latecy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "tp_tcp_connect/1000", "legendFormat": "{{target}}" }
   ]
  },
  {
   "title": "TCP Busy Sending Data (Milliseconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "tp_tcpinfo_busy_time/1000", "legendFormat": "{{target}}" }
   ]
  },
  {
   "title": "TCP Congestion Window Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "tp_tcpinfo_snd_cwnd", "legendFormat": "{{target}}" }
   ]
  },
  {
   "title": "Connect & DNS errors rates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(tp_tcp_connect_error[5m])", "legendFormat": "{{target}}  [connect]" },
    { "expr": "rate(tp_dns_resolve_error[5m])", "legendFormat": "{{target}} [dns]" }
   ]
  },
  {
   "title": "DNS Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "tp_dns_resolve/1000", "legendFormat": "{{target}}" }
   ]
  },
  {
   "title": "TCP RCV MSS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "tp_tcpinfo_rcv_mss", "legendFormat": "{{target}}" }
   ]
  },
  {
   "title": "TCP SND MSS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "tp_tcpinfo_snd_mss", "legendFormat": "{{target}}" }
   ]
  },
  {
   "title": "HTTP Request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "tp_http_request/1000", "legendFormat": "{{target}}" }
   ]
  },
  {
   "title": "HTTP Response",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "tp_http_response/1000", "legendFormat": "{{target}}" }
   ]
  },
  {
   "title": "TCP Retransmission Timeout (Milliseconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "tp_tcpinfo_rto/1000", "legendFormat": "{{target}}" }
   ]
  },
  {
   "title": "TCP Ack Timeout (milliseconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "tp_tcpinfo_ato/1000", "legendFormat": "{{target}}" }
   ]
  },
  {
   "title": "TCP Delivery Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "tp_tcpinfo_delivery_rate", "legendFormat": "{{target}}" }
   ]
  },
  {
   "title": "Path MTU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "tp_tcpinfo_path_mtu", "legendFormat": "{{target}}" }
   ]
  },
  {
   "title": "TCP Reordering Events Seen",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "tp_tcpinfo_reord_seen", "legendFormat": "{{target}}" }
   ]
  },
  {
   "title": "RFC4898 tcpEStatsStackDSACKDups",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "tp_tcpinfo_dsack_dups", "legendFormat": "{{target}}" }
   ]
  }
 ]
}